In [1]:
import ast
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
import seaborn as sns

dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

df['job_posted_date']=pd.to_datetime(df['job_posted_date'])
df['job_skills']=df['job_skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x)

In [2]:
df_in=df[(df['job_title_short']=='Data Analyst') & (df['job_country']=='India')].copy()

In [7]:
df_in=df_in.dropna(subset='salary_year_avg')
df_explode=df_in.explode("job_skills")
df_explode[['salary_year_avg','job_skills']].head(5)

       salary_year_avg job_skills
11412          50400.0     python
11412          50400.0        sql
11412          50400.0        aws
11412          50400.0      azure
11412          50400.0      excel

In [10]:
df_explode.groupby('job_skills')['salary_year_avg'].agg(['count','median']).sort_values(by='count', ascending=False)

            count    median
job_skills
sql            46   96050.0
excel          39   98500.0
python         36   96050.0
tableau        20  108087.5
r              18   79200.0
...           ...       ...
postgresql      1  165000.0
ms access       1   64600.0
mysql           1  165000.0
neo4j           1  163782.0
zoom            1  104500.0

[83 rows x 2 columns]